stages:
  - lint
ci-check:
  stage: lint
  image: node:18
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint
    - npm run format:check
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  only:
    - merge_requests
  after_script:
    - echo "All checks passed!"
